package com.louis.kitty.admin.model;

import java.util.Date;

public class Backup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_backup.id
     *
     * @mbg.generated Sat Aug 05 11:05:01 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_backup.backup_code
     *
     * @mbg.generated Sat Aug 05 11:05:01 CST 2023
     */
    private String backupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_backup.version
     *
     * @mbg.generated Sat Aug 05 11:05:01 CST 2023
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_backup.c_date
     *
     * @mbg.generated Sat Aug 05 11:05:01 CST 2023
     */
    private Date cDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_backup.id
     *
     * @return the value of sys_backup.id
     *
     * @mbg.generated Sat Aug 05 11:05:01 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_backup.id
     *
     * @param id the value for sys_backup.id
     *
     * @mbg.generated Sat Aug 05 11:05:01 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_backup.backup_code
     *
     * @return the value of sys_backup.backup_code
     *
     * @mbg.generated Sat Aug 05 11:05:01 CST 2023
     */
    public String getBackupCode() {
        return backupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_backup.backup_code
     *
     * @param backupCode the value for sys_backup.backup_code
     *
     * @mbg.generated Sat Aug 05 11:05:01 CST 2023
     */
    public void setBackupCode(String backupCode) {
        this.backupCode = backupCode == null ? null : backupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_backup.version
     *
     * @return the value of sys_backup.version
     *
     * @mbg.generated Sat Aug 05 11:05:01 CST 2023
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_backup.version
     *
     * @param version the value for sys_backup.version
     *
     * @mbg.generated Sat Aug 05 11:05:01 CST 2023
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_backup.c_date
     *
     * @return the value of sys_backup.c_date
     *
     * @mbg.generated Sat Aug 05 11:05:01 CST 2023
     */
    public Date getcDate() {
        return cDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_backup.c_date
     *
     * @param cDate the value for sys_backup.c_date
     *
     * @mbg.generated Sat Aug 05 11:05:01 CST 2023
     */
    public void setcDate(Date cDate) {
        this.cDate = cDate;
    }
}